name: Publish

on:
  push:
    branches:
      - vc-demo

env:
  REGISTRY: quay.io
  REPOSITORY: beknazar

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: get_release
        run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push Docker
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./docker/Dockerfile
#          tags: |
#            beknazar/baelp19
#          push: true
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: baelp5
          tags: latest ${{ github.sha }}
          dockerfiles: |
            ./docker/Dockerfile
          context: ./

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}